language: python
python:
  - "3.6" # command to install dependencies, requirements.txt should NOT include numpy
before_install:
  - sudo apt-get install -y ca-certificates
  - export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt #otherwise it wont download from google cloud storage.
addons:
  apt:
    update: true
install:
  - python setup.py install
  #- pip install -r requirements.txt
  - pip install -r tests/test_requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below