language: python
python:
  - "3.7" # command to install dependencies, requirements.txt should NOT include numpy
install:
  - python setup.py install
  #- pip install -r requirements.txt
  - pip install -r tests/test_requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below